# Generated by Django 5.0.4 on 2026-04-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='traits',
            field=models.JSONField(default=list, verbose_name='Traits'),
        ),
    ]
