# Generated by Django 5.0.4 on 2026-04-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_add_traits_to_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')], default=2, verbose_name='Difficulté'),
        ),
    ]
